<?xml version="1.0" encoding="utf-8"?><Database Name="accounts" Class="DataLoginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ZAKU-R44S51\SQLEXPRESS;Initial Catalog=accounts;Integrated Security=True" SettingsObjectName="LoginApp.Properties.Settings" SettingsPropertyName="accountsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.userAcc" Member="userAccs">
    <Type Name="userAcc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="facename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_faceType" Method="sp_faceType">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_verifyFace" Method="sp_verifyFace">
    <Parameter Name="key" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_verifyFaceResult">
      <Column Name="facename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertAccount" Method="sp_insertAccount">
    <Parameter Name="Fname" Parameter="fname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Mname" Parameter="mname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Lname" Parameter="lname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="passwords" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="facename" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="usertype" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_login" Method="sp_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_loginResult">
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_type" Method="sp_type">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="passwords" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>